### ISSUE TITLE
Error pulling from docker hub

### ISSUE THREAD

**Issue by alvintzheng** [Zhong-Lab-UCSD/iMARGI-Docker#3]
When I try to pull from docker hub in the software testing demo, it gives an error.
I try: docker pull zhonglab/imargi
And this is the output:
--------------------------------------------------------
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.). Using system default: https://index.docker.io/v1/
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/images/create?fromImage=zhonglab%2Fimargi&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
---------------------------------------------------------

I am using docker toolbox because my computer cannot install Docker community edition.

**Comment by frankyan** [comment]
Hi, it seems that you didn't successfully installed or start the Docker Toolbox. Could you please follow the instructions of Docker Toolbox to check it?
Besides, after you can use it, please increase the memory limit of your Docker Toolbox to at least 6GB to ensure BWA mapping step can work.
