### ISSUE TITLE
bwa_index files on tutorial

### ISSUE THREAD

**Issue by alvintzheng** [Zhong-Lab-UCSD/iMARGI-Docker#4]
![image](https://user-images.githubusercontent.com/15203641/55921721-d9545600-5bb2-11e9-9306-be6f4f3a417f.png)

On the left is what I got in my directory after unpacking the bwa_index files, and on the right is what the directory should look like according to the software testing demo. Should I rename my files, or is there something I didn't download?

**Comment by frankyan** [comment]
Sorry, it's a typo in the README. The files you got are correct.
