### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by alvintzheng** [Zhong-Lab-UCSD/iMARGI-Docker#5]
Upon inputting the command given to run the entire pipeline, shown in the software testing example, I get this output using Docker Toolbox (8gb memory enabled):

$ docker run --rm -u 1043 -v ~/imargi_example:/imargi zhonglab/imargi     imargi_wrapper.sh     -r hg38     -N test_sam
ple     -t 4     -g ./ref/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta     -i ./ref/bwa_index/bwa_index_hg38     -
1 ./data/sample_R1.fastq.gz     -2 ./data/sample_R2.fastq.gz     -o ./output
Use default max inter align gap for pairtools parsing.
Use default offset 3'.
Use default max ligation size 1000'.
================ iMARGI Pipeline BEGIN
Thu Apr 11 00:12:04 UTC 2019
\>>>>>>>>>>>>>>>> Ref: no chromsize argument. Start generating chromsize file from ./ref/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta ...
read tcp 192.168.99.1:52365->192.168.99.100:2376: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

I have tried this multiple times and have gotten the same result every time. The output says 'generating chromsize file from ./ref/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta ...' and then pauses for a few minutes. Then the rest of the output comes through showing the error.

**Comment by frankyan** [comment]
It's a problem of Docker Toolbox settings. I found a Windows laptop had similar problem.

First, could you please try to set 10 GB memory to Docker Toolbox and test?

If it doesn't work, please try to totally reinstall DockerToolbox. Although I don't know why, it can solve the problem on the computer I am testing. I am still doing more test.

remove Docker-Toolbox and VirtualBox -> reboot computer -> reinstall the Docker-Toolbox
 
Please use the latest version https://github.com/docker/toolbox/releases.

**Comment by frankyan** [comment]
On the testing machine, the previous Docker Toolbox is downloaded from Docker official site, https://docs.docker.com/toolbox/overview/, which is version 18.03. When I reinstall the DockerToolbox, I used the latest 18.09.3 version downloaded from their GItHub repo, https://github.com/docker/toolbox/releases. Then the connection issue disappeared.

Have you solved the problem?

**Comment by alvintzheng** [comment]
I am currently in class, have not yet tried the 10 gb fix.

Alvin Zheng
